[package]
name = "rust-dummy-api-actix-web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
dotenvy = "0.15.7"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
uuid = "1.19.0"
uuid-extra = "0.0.2"
